server:
  port: 6001

#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul: 
  routes: 
    goods-service: /apigateway/goods/**
  # 统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  # 忽略整个服务，对外提供接口
  ignored-services: goods-service
  # 处理http请求头为空的问题
  sensitive-headers: 